module.exports = {
    presets:["module:metro-react-native-babel-preset"],
    plugins:[
        "module:react-native-dotenv",
        [
            "dotenv-import",
            {
                moduleName:"@env",
                path:".env",
                blacklist:null,
                whitelist:null,
                safe:false,
                allowUndefined:false,
            },
        ],
        ["module-resolver",{
            alias:{
                "components":"./src/shared/components",
                "appjson":"./src/App.json",
                "data":"./src/shared/Data.json",
                "css":"./src/shared/index.js"
            }
        }],
        "react-native-reanimated/plugin",
    ],
};
